FROM ubuntu:noble

ARG DEBIAN_FRONTEND=noninteractive

# === INSTALL Node.js ===
ARG NODE \
    PLAYWRIGHT

RUN apt-get update && \
    # Install Node.js
    apt-get install -y curl wget gpg ca-certificates && \
    mkdir -p /etc/apt/keyrings && \
    curl -sL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE.x nodistro main" >> /etc/apt/sources.list.d/nodesource.list && \
    apt-get update && \
    apt-get install -y nodejs && \
    # Feature-parity with node.js base images.
    apt-get install -y --no-install-recommends git openssh-client && \
    npm install -g yarn && \
    # clean apt cache
    rm -rf /var/lib/apt/lists/* && \
    # Create the pwuser
    adduser pwuser

RUN node -v

# RUN npm install playwright@$PLAYWRIGHT

RUN npx playwright install --with-deps chromium

RUN npx playwright install --with-deps webkit

RUN npx playwright install --with-deps firefox